### ISSUE TITLE
Http Status Code 204

### ISSUE THREAD

**Issue by barbieswimcrew** [valiton/ShariffBundle#1]
Hi at all,

i'm trying to get the ShariffBundle work on my page but without any success. Might be awesome if you'd help me out.

What i did:
- i created a new symfony project and tried to install the shariffbundle via composer require. 
- got an error:
  [InvalidArgumentException]  
  Could not find package valiton/shariff-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability"
- changed the minimum-stability in the composer.json to "dev"
- after installing i activated the bundle in the appkernel and even put the configurations into my config.yml file
- by trying to navigate to /get?url=http://www.heise.de i got another error:
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  The service "valiton_shariff.shariff_controller" has a dependency on a non-existent service "fos_rest.view_handler". 
- so i went on by installing the FOSRestBundle and activated it in the appkernel
- after that another error occured:
  Neither a service called "jms_serializer.serializer" nor "serializer" is available and no serializer is explicitly configured. You must either enable the JMSSerializerBundle, enable the FrameworkBundle serializer or configure a custom serializer.  
- installed jms/serializer-bundle 

After all that no further error occured. But when i tried opening the url above chrome's network tab registered a response: Status Code 204 - No Content

I don't have any idea why this is happening... maybe you have any clue?

Thank you in advance!

**Comment by uwej711** [comment]
Currently composer should already install FOSRestBundle. You shouldn't set the minimum-stability to dev as this will give you dev versions of all the bundles. Rather `require valiton/shariff-bundle:dev-master`.
I just checked my sample app with symfony 2.3.25, the framework serializer (not JMSSerializer) and found that 204 is returned when the result is null, for example when the passed url does not match the configured domain.

Can you please paste your configuration for valiton_shariff here?

**Comment by barbieswimcrew** [comment]
Oh my god! You're my hero! I did not know that the URL could be the clue. After you wrote that the passed url could not match the configured domain i tried modifying the configured url and now it works. First i had http://www.example.com but it has to be like so: www.example.com (without protocol).

Thank you so many times!
